#!/bin/bash

if [ "yes" == "$FAIL" ]; then 
    >&2 /bin/echo "This is just a failing script."
    exit 1
fi

if [ "logout" == "$FAIL" ]; then 
    >&2 /bin/echo "No subscription found. Run 'az account set' to select a subscription."
    exit 1
fi

if [ "corrupt" == "$FAIL" ]; then 
    /bin/echo "{accessToken: ..corrupt"
    exit
fi

for arg in "$@"; do
    if [[ "$arg" == "$FAIL_IF" ]]; then
        echo "Failed"
        exit 1
    fi
done

# MacOS
EXP="$(/bin/date -v+${EXPIRE:=10S} +'%FT%T%z' 2>/dev/null)"
if [ -z "${EXP}" ]; then
  # Linux
  EXPIRE=$(/bin/echo $EXPIRE | /bin/sed 's/S/seconds/')
  EXPIRE=$(/bin/echo $EXPIRE | /bin/sed 's/M/minutes/')
  EXP=$(/bin/date --date=+${EXPIRE:=10seconds} +'%FT%T%z')
fi
# Insert colon in timezone offset for ISO 8601 compliance
EXP="${EXP:0:19}${EXP:19:3}:${EXP:22:2}"

if [ -z "${TF_AAD_TOKEN}" ]; then
    TF_AAD_TOKEN="..."
fi

/bin/echo "{
  \"accessToken\": \"${TF_AAD_TOKEN}\",
  \"expiresOn\": \"${EXP}\",
  \"subscription\": \"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\",
  \"tenant\": \"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\",
  \"tokenType\": \"Bearer\"
}"
