// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.ml;

import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Collection;
import java.util.Objects;

/**
 * <p>ModelVersion class.</p>
 *
 * @author tanmay.rustagi
 * @version $Id: $Id
 */
public class ModelVersion {
  /** Timestamp recorded when this `model_version` was created. */
  @JsonProperty("creation_timestamp")
  private Long creationTimestamp;

  /** Current stage for this `model_version`. */
  @JsonProperty("current_stage")
  private String currentStage;

  /** Description of this `model_version`. */
  @JsonProperty("description")
  private String description;

  /** Timestamp recorded when metadata for this `model_version` was last updated. */
  @JsonProperty("last_updated_timestamp")
  private Long lastUpdatedTimestamp;

  /** Unique name of the model */
  @JsonProperty("name")
  private String name;

  /**
   * MLflow run ID used when creating `model_version`, if `source` was generated by an experiment
   * run stored in MLflow tracking server.
   */
  @JsonProperty("run_id")
  private String runId;

  /** Run Link: Direct link to the run that generated this version */
  @JsonProperty("run_link")
  private String runLink;

  /**
   * URI indicating the location of the source model artifacts, used when creating `model_version`
   */
  @JsonProperty("source")
  private String source;

  /** Current status of `model_version` */
  @JsonProperty("status")
  private ModelVersionStatus status;

  /** Details on current `status`, if it is pending or failed. */
  @JsonProperty("status_message")
  private String statusMessage;

  /** Tags: Additional metadata key-value pairs for this `model_version`. */
  @JsonProperty("tags")
  private Collection<ModelVersionTag> tags;

  /** User that created this `model_version`. */
  @JsonProperty("user_id")
  private String userId;

  /** Model's version number. */
  @JsonProperty("version")
  private String version;

  /**
   * <p>Setter for the field <code>creationTimestamp</code>.</p>
   *
   * @param creationTimestamp a {@link java.lang.Long} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setCreationTimestamp(Long creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

  /**
   * <p>Getter for the field <code>creationTimestamp</code>.</p>
   *
   * @return a {@link java.lang.Long} object
   */
  public Long getCreationTimestamp() {
    return creationTimestamp;
  }

  /**
   * <p>Setter for the field <code>currentStage</code>.</p>
   *
   * @param currentStage a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setCurrentStage(String currentStage) {
    this.currentStage = currentStage;
    return this;
  }

  /**
   * <p>Getter for the field <code>currentStage</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getCurrentStage() {
    return currentStage;
  }

  /**
   * <p>Setter for the field <code>description</code>.</p>
   *
   * @param description a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setDescription(String description) {
    this.description = description;
    return this;
  }

  /**
   * <p>Getter for the field <code>description</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getDescription() {
    return description;
  }

  /**
   * <p>Setter for the field <code>lastUpdatedTimestamp</code>.</p>
   *
   * @param lastUpdatedTimestamp a {@link java.lang.Long} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setLastUpdatedTimestamp(Long lastUpdatedTimestamp) {
    this.lastUpdatedTimestamp = lastUpdatedTimestamp;
    return this;
  }

  /**
   * <p>Getter for the field <code>lastUpdatedTimestamp</code>.</p>
   *
   * @return a {@link java.lang.Long} object
   */
  public Long getLastUpdatedTimestamp() {
    return lastUpdatedTimestamp;
  }

  /**
   * <p>Setter for the field <code>name</code>.</p>
   *
   * @param name a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * <p>Getter for the field <code>name</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getName() {
    return name;
  }

  /**
   * <p>Setter for the field <code>runId</code>.</p>
   *
   * @param runId a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setRunId(String runId) {
    this.runId = runId;
    return this;
  }

  /**
   * <p>Getter for the field <code>runId</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getRunId() {
    return runId;
  }

  /**
   * <p>Setter for the field <code>runLink</code>.</p>
   *
   * @param runLink a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setRunLink(String runLink) {
    this.runLink = runLink;
    return this;
  }

  /**
   * <p>Getter for the field <code>runLink</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getRunLink() {
    return runLink;
  }

  /**
   * <p>Setter for the field <code>source</code>.</p>
   *
   * @param source a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setSource(String source) {
    this.source = source;
    return this;
  }

  /**
   * <p>Getter for the field <code>source</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getSource() {
    return source;
  }

  /**
   * <p>Setter for the field <code>status</code>.</p>
   *
   * @param status a {@link com.databricks.sdk.service.ml.ModelVersionStatus} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setStatus(ModelVersionStatus status) {
    this.status = status;
    return this;
  }

  /**
   * <p>Getter for the field <code>status</code>.</p>
   *
   * @return a {@link com.databricks.sdk.service.ml.ModelVersionStatus} object
   */
  public ModelVersionStatus getStatus() {
    return status;
  }

  /**
   * <p>Setter for the field <code>statusMessage</code>.</p>
   *
   * @param statusMessage a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

  /**
   * <p>Getter for the field <code>statusMessage</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getStatusMessage() {
    return statusMessage;
  }

  /**
   * <p>Setter for the field <code>tags</code>.</p>
   *
   * @param tags a {@link java.util.Collection} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setTags(Collection<ModelVersionTag> tags) {
    this.tags = tags;
    return this;
  }

  /**
   * <p>Getter for the field <code>tags</code>.</p>
   *
   * @return a {@link java.util.Collection} object
   */
  public Collection<ModelVersionTag> getTags() {
    return tags;
  }

  /**
   * <p>Setter for the field <code>userId</code>.</p>
   *
   * @param userId a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setUserId(String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * <p>Getter for the field <code>userId</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getUserId() {
    return userId;
  }

  /**
   * <p>Setter for the field <code>version</code>.</p>
   *
   * @param version a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.ml.ModelVersion} object
   */
  public ModelVersion setVersion(String version) {
    this.version = version;
    return this;
  }

  /**
   * <p>Getter for the field <code>version</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getVersion() {
    return version;
  }

  /** {@inheritDoc} */
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    ModelVersion that = (ModelVersion) o;
    return Objects.equals(creationTimestamp, that.creationTimestamp)
        && Objects.equals(currentStage, that.currentStage)
        && Objects.equals(description, that.description)
        && Objects.equals(lastUpdatedTimestamp, that.lastUpdatedTimestamp)
        && Objects.equals(name, that.name)
        && Objects.equals(runId, that.runId)
        && Objects.equals(runLink, that.runLink)
        && Objects.equals(source, that.source)
        && Objects.equals(status, that.status)
        && Objects.equals(statusMessage, that.statusMessage)
        && Objects.equals(tags, that.tags)
        && Objects.equals(userId, that.userId)
        && Objects.equals(version, that.version);
  }

  /** {@inheritDoc} */
  @Override
  public int hashCode() {
    return Objects.hash(
        creationTimestamp,
        currentStage,
        description,
        lastUpdatedTimestamp,
        name,
        runId,
        runLink,
        source,
        status,
        statusMessage,
        tags,
        userId,
        version);
  }

  /** {@inheritDoc} */
  @Override
  public String toString() {
    return new ToStringer(ModelVersion.class)
        .add("creationTimestamp", creationTimestamp)
        .add("currentStage", currentStage)
        .add("description", description)
        .add("lastUpdatedTimestamp", lastUpdatedTimestamp)
        .add("name", name)
        .add("runId", runId)
        .add("runLink", runLink)
        .add("source", source)
        .add("status", status)
        .add("statusMessage", statusMessage)
        .add("tags", tags)
        .add("userId", userId)
        .add("version", version)
        .toString();
  }
}
