// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.ml;

import com.databricks.sdk.support.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

@Generated
public enum RegistryWebhookEvent {
  @JsonProperty("COMMENT_CREATED")
  COMMENT_CREATED,

  @JsonProperty("MODEL_VERSION_CREATED")
  MODEL_VERSION_CREATED,

  @JsonProperty("MODEL_VERSION_TAG_SET")
  MODEL_VERSION_TAG_SET,

  @JsonProperty("MODEL_VERSION_TRANSITIONED_STAGE")
  MODEL_VERSION_TRANSITIONED_STAGE,

  @JsonProperty("MODEL_VERSION_TRANSITIONED_TO_ARCHIVED")
  MODEL_VERSION_TRANSITIONED_TO_ARCHIVED,

  @JsonProperty("MODEL_VERSION_TRANSITIONED_TO_PRODUCTION")
  MODEL_VERSION_TRANSITIONED_TO_PRODUCTION,

  @JsonProperty("MODEL_VERSION_TRANSITIONED_TO_STAGING")
  MODEL_VERSION_TRANSITIONED_TO_STAGING,

  @JsonProperty("REGISTERED_MODEL_CREATED")
  REGISTERED_MODEL_CREATED,

  @JsonProperty("TRANSITION_REQUEST_CREATED")
  TRANSITION_REQUEST_CREATED,

  @JsonProperty("TRANSITION_REQUEST_TO_ARCHIVED_CREATED")
  TRANSITION_REQUEST_TO_ARCHIVED_CREATED,

  @JsonProperty("TRANSITION_REQUEST_TO_PRODUCTION_CREATED")
  TRANSITION_REQUEST_TO_PRODUCTION_CREATED,

  @JsonProperty("TRANSITION_REQUEST_TO_STAGING_CREATED")
  TRANSITION_REQUEST_TO_STAGING_CREATED,
}
