// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.billing;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.QueryParam;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

@Generated
public class UpdateUsagePolicyRequest {
  /** DEPRECATED. This is redundant field as LimitConfig is part of the UsagePolicy */
  @JsonIgnore
  @QueryParam("limit_config")
  private LimitConfig limitConfig;

  /** The policy to update. `creator_user_id` cannot be specified in the request. */
  @JsonProperty("policy")
  private UsagePolicy policy;

  /** The Id of the policy. This field is generated by Databricks and globally unique. */
  @JsonIgnore private String policyId;

  public UpdateUsagePolicyRequest setLimitConfig(LimitConfig limitConfig) {
    this.limitConfig = limitConfig;
    return this;
  }

  public LimitConfig getLimitConfig() {
    return limitConfig;
  }

  public UpdateUsagePolicyRequest setPolicy(UsagePolicy policy) {
    this.policy = policy;
    return this;
  }

  public UsagePolicy getPolicy() {
    return policy;
  }

  public UpdateUsagePolicyRequest setPolicyId(String policyId) {
    this.policyId = policyId;
    return this;
  }

  public String getPolicyId() {
    return policyId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    UpdateUsagePolicyRequest that = (UpdateUsagePolicyRequest) o;
    return Objects.equals(limitConfig, that.limitConfig)
        && Objects.equals(policy, that.policy)
        && Objects.equals(policyId, that.policyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limitConfig, policy, policyId);
  }

  @Override
  public String toString() {
    return new ToStringer(UpdateUsagePolicyRequest.class)
        .add("limitConfig", limitConfig)
        .add("policy", policy)
        .add("policyId", policyId)
        .toString();
  }
}
