// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.billing;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Collection;
import java.util.Objects;

/** Contains the UsagePolicy details (same structure as BudgetPolicy) */
@Generated
public class UsagePolicy {
  /** List of workspaces that this usage policy will be exclusively bound to. */
  @JsonProperty("binding_workspace_ids")
  private Collection<Long> bindingWorkspaceIds;

  /** A list of tags defined by the customer. At most 20 entries are allowed per policy. */
  @JsonProperty("custom_tags")
  private Collection<com.databricks.sdk.service.compute.CustomPolicyTag> customTags;

  /** The Id of the policy. This field is generated by Databricks and globally unique. */
  @JsonProperty("policy_id")
  private String policyId;

  /** The name of the policy. */
  @JsonProperty("policy_name")
  private String policyName;

  public UsagePolicy setBindingWorkspaceIds(Collection<Long> bindingWorkspaceIds) {
    this.bindingWorkspaceIds = bindingWorkspaceIds;
    return this;
  }

  public Collection<Long> getBindingWorkspaceIds() {
    return bindingWorkspaceIds;
  }

  public UsagePolicy setCustomTags(
      Collection<com.databricks.sdk.service.compute.CustomPolicyTag> customTags) {
    this.customTags = customTags;
    return this;
  }

  public Collection<com.databricks.sdk.service.compute.CustomPolicyTag> getCustomTags() {
    return customTags;
  }

  public UsagePolicy setPolicyId(String policyId) {
    this.policyId = policyId;
    return this;
  }

  public String getPolicyId() {
    return policyId;
  }

  public UsagePolicy setPolicyName(String policyName) {
    this.policyName = policyName;
    return this;
  }

  public String getPolicyName() {
    return policyName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    UsagePolicy that = (UsagePolicy) o;
    return Objects.equals(bindingWorkspaceIds, that.bindingWorkspaceIds)
        && Objects.equals(customTags, that.customTags)
        && Objects.equals(policyId, that.policyId)
        && Objects.equals(policyName, that.policyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bindingWorkspaceIds, customTags, policyId, policyName);
  }

  @Override
  public String toString() {
    return new ToStringer(UsagePolicy.class)
        .add("bindingWorkspaceIds", bindingWorkspaceIds)
        .add("customTags", customTags)
        .add("policyId", policyId)
        .add("policyName", policyName)
        .toString();
  }
}
