// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.bundledeployments;

import com.databricks.sdk.support.Generated;

/** Type of a deployment resource. */
@Generated
public enum DeploymentResourceType {
  DEPLOYMENT_RESOURCE_TYPE_ALERT,
  DEPLOYMENT_RESOURCE_TYPE_APP,
  DEPLOYMENT_RESOURCE_TYPE_CATALOG,
  DEPLOYMENT_RESOURCE_TYPE_CLUSTER,
  DEPLOYMENT_RESOURCE_TYPE_DASHBOARD,
  DEPLOYMENT_RESOURCE_TYPE_DATABASE_CATALOG,
  DEPLOYMENT_RESOURCE_TYPE_DATABASE_INSTANCE,
  DEPLOYMENT_RESOURCE_TYPE_EXPERIMENT,
  DEPLOYMENT_RESOURCE_TYPE_EXTERNAL_LOCATION,
  DEPLOYMENT_RESOURCE_TYPE_JOB,
  DEPLOYMENT_RESOURCE_TYPE_MODEL,
  DEPLOYMENT_RESOURCE_TYPE_MODEL_SERVING_ENDPOINT,
  DEPLOYMENT_RESOURCE_TYPE_PIPELINE,
  DEPLOYMENT_RESOURCE_TYPE_POSTGRES_BRANCH,
  DEPLOYMENT_RESOURCE_TYPE_POSTGRES_ENDPOINT,
  DEPLOYMENT_RESOURCE_TYPE_POSTGRES_PROJECT,
  DEPLOYMENT_RESOURCE_TYPE_QUALITY_MONITOR,
  DEPLOYMENT_RESOURCE_TYPE_REGISTERED_MODEL,
  DEPLOYMENT_RESOURCE_TYPE_SCHEMA,
  DEPLOYMENT_RESOURCE_TYPE_SECRET_SCOPE,
  DEPLOYMENT_RESOURCE_TYPE_SQL_WAREHOUSE,
  DEPLOYMENT_RESOURCE_TYPE_SYNCED_DATABASE_TABLE,
  DEPLOYMENT_RESOURCE_TYPE_VOLUME,
}
