// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.compute;

import com.databricks.sdk.support.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/** status code indicating why the cluster was terminated */
@Generated
public enum TerminationReasonCode {
  @JsonProperty("ABUSE_DETECTED")
  ABUSE_DETECTED,

  @JsonProperty("ATTACH_PROJECT_FAILURE")
  ATTACH_PROJECT_FAILURE,

  @JsonProperty("AWS_AUTHORIZATION_FAILURE")
  AWS_AUTHORIZATION_FAILURE,

  @JsonProperty("AWS_INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET_FAILURE")
  AWS_INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET_FAILURE,

  @JsonProperty("AWS_INSUFFICIENT_INSTANCE_CAPACITY_FAILURE")
  AWS_INSUFFICIENT_INSTANCE_CAPACITY_FAILURE,

  @JsonProperty("AWS_MAX_SPOT_INSTANCE_COUNT_EXCEEDED_FAILURE")
  AWS_MAX_SPOT_INSTANCE_COUNT_EXCEEDED_FAILURE,

  @JsonProperty("AWS_REQUEST_LIMIT_EXCEEDED")
  AWS_REQUEST_LIMIT_EXCEEDED,

  @JsonProperty("AWS_UNSUPPORTED_FAILURE")
  AWS_UNSUPPORTED_FAILURE,

  @JsonProperty("AZURE_BYOK_KEY_PERMISSION_FAILURE")
  AZURE_BYOK_KEY_PERMISSION_FAILURE,

  @JsonProperty("AZURE_EPHEMERAL_DISK_FAILURE")
  AZURE_EPHEMERAL_DISK_FAILURE,

  @JsonProperty("AZURE_INVALID_DEPLOYMENT_TEMPLATE")
  AZURE_INVALID_DEPLOYMENT_TEMPLATE,

  @JsonProperty("AZURE_OPERATION_NOT_ALLOWED_EXCEPTION")
  AZURE_OPERATION_NOT_ALLOWED_EXCEPTION,

  @JsonProperty("AZURE_QUOTA_EXCEEDED_EXCEPTION")
  AZURE_QUOTA_EXCEEDED_EXCEPTION,

  @JsonProperty("AZURE_RESOURCE_MANAGER_THROTTLING")
  AZURE_RESOURCE_MANAGER_THROTTLING,

  @JsonProperty("AZURE_RESOURCE_PROVIDER_THROTTLING")
  AZURE_RESOURCE_PROVIDER_THROTTLING,

  @JsonProperty("AZURE_UNEXPECTED_DEPLOYMENT_TEMPLATE_FAILURE")
  AZURE_UNEXPECTED_DEPLOYMENT_TEMPLATE_FAILURE,

  @JsonProperty("AZURE_VM_EXTENSION_FAILURE")
  AZURE_VM_EXTENSION_FAILURE,

  @JsonProperty("AZURE_VNET_CONFIGURATION_FAILURE")
  AZURE_VNET_CONFIGURATION_FAILURE,

  @JsonProperty("BOOTSTRAP_TIMEOUT")
  BOOTSTRAP_TIMEOUT,

  @JsonProperty("BOOTSTRAP_TIMEOUT_CLOUD_PROVIDER_EXCEPTION")
  BOOTSTRAP_TIMEOUT_CLOUD_PROVIDER_EXCEPTION,

  @JsonProperty("CLOUD_PROVIDER_DISK_SETUP_FAILURE")
  CLOUD_PROVIDER_DISK_SETUP_FAILURE,

  @JsonProperty("CLOUD_PROVIDER_LAUNCH_FAILURE")
  CLOUD_PROVIDER_LAUNCH_FAILURE,

  @JsonProperty("CLOUD_PROVIDER_RESOURCE_STOCKOUT")
  CLOUD_PROVIDER_RESOURCE_STOCKOUT,

  @JsonProperty("CLOUD_PROVIDER_SHUTDOWN")
  CLOUD_PROVIDER_SHUTDOWN,

  @JsonProperty("COMMUNICATION_LOST")
  COMMUNICATION_LOST,

  @JsonProperty("CONTAINER_LAUNCH_FAILURE")
  CONTAINER_LAUNCH_FAILURE,

  @JsonProperty("CONTROL_PLANE_REQUEST_FAILURE")
  CONTROL_PLANE_REQUEST_FAILURE,

  @JsonProperty("DATABASE_CONNECTION_FAILURE")
  DATABASE_CONNECTION_FAILURE,

  @JsonProperty("DBFS_COMPONENT_UNHEALTHY")
  DBFS_COMPONENT_UNHEALTHY,

  @JsonProperty("DOCKER_IMAGE_PULL_FAILURE")
  DOCKER_IMAGE_PULL_FAILURE,

  @JsonProperty("DRIVER_UNREACHABLE")
  DRIVER_UNREACHABLE,

  @JsonProperty("DRIVER_UNRESPONSIVE")
  DRIVER_UNRESPONSIVE,

  @JsonProperty("EXECUTION_COMPONENT_UNHEALTHY")
  EXECUTION_COMPONENT_UNHEALTHY,

  @JsonProperty("GCP_QUOTA_EXCEEDED")
  GCP_QUOTA_EXCEEDED,

  @JsonProperty("GCP_SERVICE_ACCOUNT_DELETED")
  GCP_SERVICE_ACCOUNT_DELETED,

  @JsonProperty("GLOBAL_INIT_SCRIPT_FAILURE")
  GLOBAL_INIT_SCRIPT_FAILURE,

  @JsonProperty("HIVE_METASTORE_PROVISIONING_FAILURE")
  HIVE_METASTORE_PROVISIONING_FAILURE,

  @JsonProperty("IMAGE_PULL_PERMISSION_DENIED")
  IMAGE_PULL_PERMISSION_DENIED,

  @JsonProperty("INACTIVITY")
  INACTIVITY,

  @JsonProperty("INIT_SCRIPT_FAILURE")
  INIT_SCRIPT_FAILURE,

  @JsonProperty("INSTANCE_POOL_CLUSTER_FAILURE")
  INSTANCE_POOL_CLUSTER_FAILURE,

  @JsonProperty("INSTANCE_UNREACHABLE")
  INSTANCE_UNREACHABLE,

  @JsonProperty("INTERNAL_ERROR")
  INTERNAL_ERROR,

  @JsonProperty("INVALID_ARGUMENT")
  INVALID_ARGUMENT,

  @JsonProperty("INVALID_SPARK_IMAGE")
  INVALID_SPARK_IMAGE,

  @JsonProperty("IP_EXHAUSTION_FAILURE")
  IP_EXHAUSTION_FAILURE,

  @JsonProperty("JOB_FINISHED")
  JOB_FINISHED,

  @JsonProperty("K8S_AUTOSCALING_FAILURE")
  KS_AUTOSCALING_FAILURE,

  @JsonProperty("K8S_DBR_CLUSTER_LAUNCH_TIMEOUT")
  KS_DBR_CLUSTER_LAUNCH_TIMEOUT,

  @JsonProperty("METASTORE_COMPONENT_UNHEALTHY")
  METASTORE_COMPONENT_UNHEALTHY,

  @JsonProperty("NEPHOS_RESOURCE_MANAGEMENT")
  NEPHOS_RESOURCE_MANAGEMENT,

  @JsonProperty("NETWORK_CONFIGURATION_FAILURE")
  NETWORK_CONFIGURATION_FAILURE,

  @JsonProperty("NFS_MOUNT_FAILURE")
  NFS_MOUNT_FAILURE,

  @JsonProperty("NPIP_TUNNEL_SETUP_FAILURE")
  NPIP_TUNNEL_SETUP_FAILURE,

  @JsonProperty("NPIP_TUNNEL_TOKEN_FAILURE")
  NPIP_TUNNEL_TOKEN_FAILURE,

  @JsonProperty("REQUEST_REJECTED")
  REQUEST_REJECTED,

  @JsonProperty("REQUEST_THROTTLED")
  REQUEST_THROTTLED,

  @JsonProperty("SECRET_RESOLUTION_ERROR")
  SECRET_RESOLUTION_ERROR,

  @JsonProperty("SECURITY_DAEMON_REGISTRATION_EXCEPTION")
  SECURITY_DAEMON_REGISTRATION_EXCEPTION,

  @JsonProperty("SELF_BOOTSTRAP_FAILURE")
  SELF_BOOTSTRAP_FAILURE,

  @JsonProperty("SKIPPED_SLOW_NODES")
  SKIPPED_SLOW_NODES,

  @JsonProperty("SLOW_IMAGE_DOWNLOAD")
  SLOW_IMAGE_DOWNLOAD,

  @JsonProperty("SPARK_ERROR")
  SPARK_ERROR,

  @JsonProperty("SPARK_IMAGE_DOWNLOAD_FAILURE")
  SPARK_IMAGE_DOWNLOAD_FAILURE,

  @JsonProperty("SPARK_STARTUP_FAILURE")
  SPARK_STARTUP_FAILURE,

  @JsonProperty("SPOT_INSTANCE_TERMINATION")
  SPOT_INSTANCE_TERMINATION,

  @JsonProperty("STORAGE_DOWNLOAD_FAILURE")
  STORAGE_DOWNLOAD_FAILURE,

  @JsonProperty("STS_CLIENT_SETUP_FAILURE")
  STS_CLIENT_SETUP_FAILURE,

  @JsonProperty("SUBNET_EXHAUSTED_FAILURE")
  SUBNET_EXHAUSTED_FAILURE,

  @JsonProperty("TEMPORARILY_UNAVAILABLE")
  TEMPORARILY_UNAVAILABLE,

  @JsonProperty("TRIAL_EXPIRED")
  TRIAL_EXPIRED,

  @JsonProperty("UNEXPECTED_LAUNCH_FAILURE")
  UNEXPECTED_LAUNCH_FAILURE,

  @JsonProperty("UNKNOWN")
  UNKNOWN,

  @JsonProperty("UNSUPPORTED_INSTANCE_TYPE")
  UNSUPPORTED_INSTANCE_TYPE,

  @JsonProperty("UPDATE_INSTANCE_PROFILE_FAILURE")
  UPDATE_INSTANCE_PROFILE_FAILURE,

  @JsonProperty("USER_REQUEST")
  USER_REQUEST,

  @JsonProperty("WORKER_SETUP_FAILURE")
  WORKER_SETUP_FAILURE,

  @JsonProperty("WORKSPACE_CANCELLED_ERROR")
  WORKSPACE_CANCELLED_ERROR,

  @JsonProperty("WORKSPACE_CONFIGURATION_ERROR")
  WORKSPACE_CONFIGURATION_ERROR,
}
