// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.dashboards;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/** Genie AI Response */
@Generated
public class GenieAttachment {
  /** Attachment ID */
  @JsonProperty("attachment_id")
  private String attachmentId;

  /** Query Attachment if Genie responds with a SQL query */
  @JsonProperty("query")
  private GenieQueryAttachment query;

  /** Follow-up questions suggested by Genie */
  @JsonProperty("suggested_questions")
  private GenieSuggestedQuestionsAttachment suggestedQuestions;

  /**
   * Text Attachment if Genie responds with text This also contains the final summary when
   * available.
   */
  @JsonProperty("text")
  private TextAttachment text;

  /** Visualization generated by Genie, if requested via `enable_visualization` */
  @JsonProperty("viz")
  private GenieVizAttachment viz;

  public GenieAttachment setAttachmentId(String attachmentId) {
    this.attachmentId = attachmentId;
    return this;
  }

  public String getAttachmentId() {
    return attachmentId;
  }

  public GenieAttachment setQuery(GenieQueryAttachment query) {
    this.query = query;
    return this;
  }

  public GenieQueryAttachment getQuery() {
    return query;
  }

  public GenieAttachment setSuggestedQuestions(
      GenieSuggestedQuestionsAttachment suggestedQuestions) {
    this.suggestedQuestions = suggestedQuestions;
    return this;
  }

  public GenieSuggestedQuestionsAttachment getSuggestedQuestions() {
    return suggestedQuestions;
  }

  public GenieAttachment setText(TextAttachment text) {
    this.text = text;
    return this;
  }

  public TextAttachment getText() {
    return text;
  }

  public GenieAttachment setViz(GenieVizAttachment viz) {
    this.viz = viz;
    return this;
  }

  public GenieVizAttachment getViz() {
    return viz;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    GenieAttachment that = (GenieAttachment) o;
    return Objects.equals(attachmentId, that.attachmentId)
        && Objects.equals(query, that.query)
        && Objects.equals(suggestedQuestions, that.suggestedQuestions)
        && Objects.equals(text, that.text)
        && Objects.equals(viz, that.viz);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachmentId, query, suggestedQuestions, text, viz);
  }

  @Override
  public String toString() {
    return new ToStringer(GenieAttachment.class)
        .add("attachmentId", attachmentId)
        .add("query", query)
        .add("suggestedQuestions", suggestedQuestions)
        .add("text", text)
        .add("viz", viz)
        .toString();
  }
}
