// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.dashboards;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/**
 * Visualization generated by Genie for a query result. Use the attachment ID with the download
 * visualization API to retrieve the rendered image.
 */
@Generated
public class GenieVizAttachment {
  /** The ID of the query attachment the visualization was generated from */
  @JsonProperty("query_attachment_id")
  private String queryAttachmentId;

  /** Name of the visualization */
  @JsonProperty("title")
  private String title;

  public GenieVizAttachment setQueryAttachmentId(String queryAttachmentId) {
    this.queryAttachmentId = queryAttachmentId;
    return this;
  }

  public String getQueryAttachmentId() {
    return queryAttachmentId;
  }

  public GenieVizAttachment setTitle(String title) {
    this.title = title;
    return this;
  }

  public String getTitle() {
    return title;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    GenieVizAttachment that = (GenieVizAttachment) o;
    return Objects.equals(queryAttachmentId, that.queryAttachmentId)
        && Objects.equals(title, that.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryAttachmentId, title);
  }

  @Override
  public String toString() {
    return new ToStringer(GenieVizAttachment.class)
        .add("queryAttachmentId", queryAttachmentId)
        .add("title", title)
        .toString();
  }
}
