// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.dashboards;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Collection;
import java.util.Objects;

/** Shows detailed information for an evaluation result. */
@Generated
public class GenieEvalResultDetails {
  /** The actual response generated by Genie. */
  @JsonProperty("actual_response")
  private Collection<GenieEvalResponse> actualResponse;

  /** Assessment of the evaluation result: good, bad, or needs review */
  @JsonProperty("assessment")
  private GenieEvalAssessment assessment;

  /**
   * Reasons for the assessment score.
   *
   * <p>Assessment reasons describe why a Genie response was scored as BAD.
   *
   * <p>Deterministic values (compared against the ground truth result): - EMPTY_RESULT: Genie's
   * generated SQL results were empty for this benchmark question. - RESULT_MISSING_ROWS: Genie's
   * generated SQL response is missing rows from the provided ground truth SQL. - RESULT_EXTRA_ROWS:
   * Genie's generated SQL response has more rows than the provided ground truth SQL. -
   * RESULT_MISSING_COLUMNS: Genie's generated SQL response is missing columns from the provided
   * ground truth SQL. - RESULT_EXTRA_COLUMNS: Genie's generated SQL response has more columns than
   * the provided ground truth SQL. - SINGLE_CELL_DIFFERENCE: Single value result was produced but
   * differs from ground truth result. - EMPTY_GOOD_SQL: The benchmark SQL returned an empty result.
   * - COLUMN_TYPE_DIFFERENCE: The values between the results match but the column type is
   * different.
   *
   * <p>LLM judge ratings explain the factors driving BAD results: -
   * LLM_JUDGE_MISSING_OR_INCORRECT_FILTER: Genie's generated SQL is missing a WHERE clause
   * condition or has incorrect filter logic that excludes/includes wrong data. -
   * LLM_JUDGE_INCOMPLETE_OR_PARTIAL_OUTPUT: Genie's generated SQL returns only some of the
   * requested data or columns, missing parts of what the ground truth SQL returns. -
   * LLM_JUDGE_MISINTERPRETATION_OF_USER_REQUEST: Genie's generated SQL fundamentally misunderstands
   * what the user is asking for, addressing the wrong question or goal. -
   * LLM_JUDGE_INSTRUCTION_COMPLIANCE_OR_MISSING_BUSINESS_LOGIC: Genie's generated SQL fails to
   * apply specified instructions or business logic that should be followed. -
   * LLM_JUDGE_INCORRECT_METRIC_CALCULATION: Genie's generated SQL uses incorrect logic or makes
   * wrong assumptions when calculating metrics. - LLM_JUDGE_INCORRECT_TABLE_OR_FIELD_USAGE: Genie's
   * generated SQL references wrong tables, columns, or uses fields that don't match the ground
   * truth SQL's intent. - LLM_JUDGE_INCORRECT_FUNCTION_USAGE: Genie's generated SQL uses SQL
   * functions incorrectly or inappropriately (wrong parameters, wrong function for the task, etc.).
   * - LLM_JUDGE_MISSING_OR_INCORRECT_JOIN: Genie's generated SQL is missing necessary joins between
   * tables or has incorrect join conditions/types that produce wrong results. -
   * LLM_JUDGE_MISSING_OR_INCORRECT_AGGREGATION: Genie's generated SQL is missing GROUP BY clauses
   * or has incorrect grouping that doesn't match the requested aggregation level. -
   * LLM_JUDGE_FORMATTING_ERROR: Genie's generated SQL output has incorrect formatting, ordering
   * (ORDER BY), or presentation issues that don't match expectations. - LLM_JUDGE_OTHER: LLM judge
   * identified an error that doesn't fall into other categories.
   *
   * <p>Deprecated LLM judge values (kept for backward compatibility, do not use): -
   * LLM_JUDGE_MISSING_JOIN (deprecated) - LLM_JUDGE_WRONG_FILTER (deprecated) -
   * LLM_JUDGE_WRONG_AGGREGATION (deprecated) - LLM_JUDGE_WRONG_COLUMNS (deprecated) -
   * LLM_JUDGE_SYNTAX_ERROR (deprecated) - LLM_JUDGE_SEMANTIC_ERROR (deprecated)
   */
  @JsonProperty("assessment_reasons")
  private Collection<ScoreReason> assessmentReasons;

  /** The ID of the benchmark question that was evaluated. */
  @JsonProperty("benchmark_question_id")
  private String benchmarkQuestionId;

  /** Current status of the evaluation run. */
  @JsonProperty("eval_run_status")
  private EvaluationStatusType evalRunStatus;

  /** The expected responses from the benchmark. */
  @JsonProperty("expected_response")
  private Collection<GenieEvalResponse> expectedResponse;

  /** Whether this evaluation was manually assessed. */
  @JsonProperty("manual_assessment")
  private Boolean manualAssessment;

  /** The unique identifier for the evaluation result. */
  @JsonProperty("result_id")
  private String resultId;

  /** The ID of the space the evaluation result belongs to. */
  @JsonProperty("space_id")
  private String spaceId;

  public GenieEvalResultDetails setActualResponse(Collection<GenieEvalResponse> actualResponse) {
    this.actualResponse = actualResponse;
    return this;
  }

  public Collection<GenieEvalResponse> getActualResponse() {
    return actualResponse;
  }

  public GenieEvalResultDetails setAssessment(GenieEvalAssessment assessment) {
    this.assessment = assessment;
    return this;
  }

  public GenieEvalAssessment getAssessment() {
    return assessment;
  }

  public GenieEvalResultDetails setAssessmentReasons(Collection<ScoreReason> assessmentReasons) {
    this.assessmentReasons = assessmentReasons;
    return this;
  }

  public Collection<ScoreReason> getAssessmentReasons() {
    return assessmentReasons;
  }

  public GenieEvalResultDetails setBenchmarkQuestionId(String benchmarkQuestionId) {
    this.benchmarkQuestionId = benchmarkQuestionId;
    return this;
  }

  public String getBenchmarkQuestionId() {
    return benchmarkQuestionId;
  }

  public GenieEvalResultDetails setEvalRunStatus(EvaluationStatusType evalRunStatus) {
    this.evalRunStatus = evalRunStatus;
    return this;
  }

  public EvaluationStatusType getEvalRunStatus() {
    return evalRunStatus;
  }

  public GenieEvalResultDetails setExpectedResponse(
      Collection<GenieEvalResponse> expectedResponse) {
    this.expectedResponse = expectedResponse;
    return this;
  }

  public Collection<GenieEvalResponse> getExpectedResponse() {
    return expectedResponse;
  }

  public GenieEvalResultDetails setManualAssessment(Boolean manualAssessment) {
    this.manualAssessment = manualAssessment;
    return this;
  }

  public Boolean getManualAssessment() {
    return manualAssessment;
  }

  public GenieEvalResultDetails setResultId(String resultId) {
    this.resultId = resultId;
    return this;
  }

  public String getResultId() {
    return resultId;
  }

  public GenieEvalResultDetails setSpaceId(String spaceId) {
    this.spaceId = spaceId;
    return this;
  }

  public String getSpaceId() {
    return spaceId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    GenieEvalResultDetails that = (GenieEvalResultDetails) o;
    return Objects.equals(actualResponse, that.actualResponse)
        && Objects.equals(assessment, that.assessment)
        && Objects.equals(assessmentReasons, that.assessmentReasons)
        && Objects.equals(benchmarkQuestionId, that.benchmarkQuestionId)
        && Objects.equals(evalRunStatus, that.evalRunStatus)
        && Objects.equals(expectedResponse, that.expectedResponse)
        && Objects.equals(manualAssessment, that.manualAssessment)
        && Objects.equals(resultId, that.resultId)
        && Objects.equals(spaceId, that.spaceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        actualResponse,
        assessment,
        assessmentReasons,
        benchmarkQuestionId,
        evalRunStatus,
        expectedResponse,
        manualAssessment,
        resultId,
        spaceId);
  }

  @Override
  public String toString() {
    return new ToStringer(GenieEvalResultDetails.class)
        .add("actualResponse", actualResponse)
        .add("assessment", assessment)
        .add("assessmentReasons", assessmentReasons)
        .add("benchmarkQuestionId", benchmarkQuestionId)
        .add("evalRunStatus", evalRunStatus)
        .add("expectedResponse", expectedResponse)
        .add("manualAssessment", manualAssessment)
        .add("resultId", resultId)
        .add("spaceId", spaceId)
        .toString();
  }
}
