// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.dashboards;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Collection;
import java.util.Objects;

/** Shows detailed information for an evaluation result. */
@Generated
public class GenieEvalResultDetails {
  /** The actual response generated by Genie. */
  @JsonProperty("actual_response")
  private Collection<GenieEvalResponse> actualResponse;

  /** Assessment of the evaluation result: good, bad, or needs review */
  @JsonProperty("assessment")
  private GenieEvalAssessment assessment;

  /** Reasons for the assessment score. */
  @JsonProperty("assessment_reasons")
  private Collection<ScoreReason> assessmentReasons;

  /** The ID of the benchmark question that was evaluated. */
  @JsonProperty("benchmark_question_id")
  private String benchmarkQuestionId;

  /** Current status of the evaluation run. */
  @JsonProperty("eval_run_status")
  private EvaluationStatusType evalRunStatus;

  /** The expected responses from the benchmark. */
  @JsonProperty("expected_response")
  private Collection<GenieEvalResponse> expectedResponse;

  /** Whether this evaluation was manually assessed. */
  @JsonProperty("manual_assessment")
  private Boolean manualAssessment;

  /** The unique identifier for the evaluation result. */
  @JsonProperty("result_id")
  private String resultId;

  /** The ID of the space the evaluation result belongs to. */
  @JsonProperty("space_id")
  private String spaceId;

  public GenieEvalResultDetails setActualResponse(Collection<GenieEvalResponse> actualResponse) {
    this.actualResponse = actualResponse;
    return this;
  }

  public Collection<GenieEvalResponse> getActualResponse() {
    return actualResponse;
  }

  public GenieEvalResultDetails setAssessment(GenieEvalAssessment assessment) {
    this.assessment = assessment;
    return this;
  }

  public GenieEvalAssessment getAssessment() {
    return assessment;
  }

  public GenieEvalResultDetails setAssessmentReasons(Collection<ScoreReason> assessmentReasons) {
    this.assessmentReasons = assessmentReasons;
    return this;
  }

  public Collection<ScoreReason> getAssessmentReasons() {
    return assessmentReasons;
  }

  public GenieEvalResultDetails setBenchmarkQuestionId(String benchmarkQuestionId) {
    this.benchmarkQuestionId = benchmarkQuestionId;
    return this;
  }

  public String getBenchmarkQuestionId() {
    return benchmarkQuestionId;
  }

  public GenieEvalResultDetails setEvalRunStatus(EvaluationStatusType evalRunStatus) {
    this.evalRunStatus = evalRunStatus;
    return this;
  }

  public EvaluationStatusType getEvalRunStatus() {
    return evalRunStatus;
  }

  public GenieEvalResultDetails setExpectedResponse(
      Collection<GenieEvalResponse> expectedResponse) {
    this.expectedResponse = expectedResponse;
    return this;
  }

  public Collection<GenieEvalResponse> getExpectedResponse() {
    return expectedResponse;
  }

  public GenieEvalResultDetails setManualAssessment(Boolean manualAssessment) {
    this.manualAssessment = manualAssessment;
    return this;
  }

  public Boolean getManualAssessment() {
    return manualAssessment;
  }

  public GenieEvalResultDetails setResultId(String resultId) {
    this.resultId = resultId;
    return this;
  }

  public String getResultId() {
    return resultId;
  }

  public GenieEvalResultDetails setSpaceId(String spaceId) {
    this.spaceId = spaceId;
    return this;
  }

  public String getSpaceId() {
    return spaceId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    GenieEvalResultDetails that = (GenieEvalResultDetails) o;
    return Objects.equals(actualResponse, that.actualResponse)
        && Objects.equals(assessment, that.assessment)
        && Objects.equals(assessmentReasons, that.assessmentReasons)
        && Objects.equals(benchmarkQuestionId, that.benchmarkQuestionId)
        && Objects.equals(evalRunStatus, that.evalRunStatus)
        && Objects.equals(expectedResponse, that.expectedResponse)
        && Objects.equals(manualAssessment, that.manualAssessment)
        && Objects.equals(resultId, that.resultId)
        && Objects.equals(spaceId, that.spaceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        actualResponse,
        assessment,
        assessmentReasons,
        benchmarkQuestionId,
        evalRunStatus,
        expectedResponse,
        manualAssessment,
        resultId,
        spaceId);
  }

  @Override
  public String toString() {
    return new ToStringer(GenieEvalResultDetails.class)
        .add("actualResponse", actualResponse)
        .add("assessment", assessment)
        .add("assessmentReasons", assessmentReasons)
        .add("benchmarkQuestionId", benchmarkQuestionId)
        .add("evalRunStatus", evalRunStatus)
        .add("expectedResponse", expectedResponse)
        .add("manualAssessment", manualAssessment)
        .add("resultId", resultId)
        .add("spaceId", spaceId)
        .toString();
  }
}
