// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.dashboards;

import com.databricks.sdk.support.Generated;

@Generated
public enum ScoreReason {
  COLUMN_TYPE_DIFFERENCE,
  EMPTY_GOOD_SQL,
  EMPTY_RESULT,
  LLM_JUDGE_FORMATTING_ERROR,
  LLM_JUDGE_INCOMPLETE_OR_PARTIAL_OUTPUT,
  LLM_JUDGE_INCORRECT_FUNCTION_USAGE,
  LLM_JUDGE_INCORRECT_METRIC_CALCULATION,
  LLM_JUDGE_INCORRECT_TABLE_OR_FIELD_USAGE,
  LLM_JUDGE_INSTRUCTION_COMPLIANCE_OR_MISSING_BUSINESS_LOGIC,
  LLM_JUDGE_MISINTERPRETATION_OF_USER_REQUEST,
  LLM_JUDGE_MISSING_JOIN,
  LLM_JUDGE_MISSING_OR_INCORRECT_AGGREGATION,
  LLM_JUDGE_MISSING_OR_INCORRECT_FILTER,
  LLM_JUDGE_MISSING_OR_INCORRECT_JOIN,
  LLM_JUDGE_OTHER,
  LLM_JUDGE_SEMANTIC_ERROR,
  LLM_JUDGE_SYNTAX_ERROR,
  LLM_JUDGE_WRONG_AGGREGATION,
  LLM_JUDGE_WRONG_COLUMNS,
  LLM_JUDGE_WRONG_FILTER,
  RESULT_EXTRA_COLUMNS,
  RESULT_EXTRA_ROWS,
  RESULT_MISSING_COLUMNS,
  RESULT_MISSING_ROWS,
  SINGLE_CELL_DIFFERENCE,
}
