// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.sql;

public enum ServiceErrorCode {
  ABORTED,
  ALREADY_EXISTS,
  BAD_REQUEST,
  CANCELLED,
  DEADLINE_EXCEEDED,
  INTERNAL_ERROR,
  IO_ERROR,
  NOT_FOUND,
  RESOURCE_EXHAUSTED,
  SERVICE_UNDER_MAINTENANCE,
  TEMPORARILY_UNAVAILABLE,
  UNAUTHENTICATED,
  UNKNOWN,
  WORKSPACE_TEMPORARILY_UNAVAILABLE,
}
