// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.catalog;

import com.databricks.sdk.support.Generated;

/** Data source format */
@Generated
public enum DataSourceFormat {
  AVRO,
  BIGQUERY_FORMAT,
  CSV,
  DATABRICKS_FORMAT,
  DATABRICKS_ROW_STORE_FORMAT,
  DELTA,
  DELTASHARING,
  DELTA_UNIFORM_HUDI,
  DELTA_UNIFORM_ICEBERG,
  HIVE,
  ICEBERG,
  JSON,
  MONGODB_FORMAT,
  MYSQL_FORMAT,
  NETSUITE_FORMAT,
  ORACLE_FORMAT,
  ORC,
  PARQUET,
  POSTGRESQL_FORMAT,
  REDSHIFT_FORMAT,
  SALESFORCE_DATA_CLOUD_FORMAT,
  SALESFORCE_FORMAT,
  SNOWFLAKE_FORMAT,
  SQLDW_FORMAT,
  SQLSERVER_FORMAT,
  TERADATA_FORMAT,
  TEXT,
  UNITY_CATALOG,
  VECTOR_INDEX_FORMAT,
  WORKDAY_RAAS_FORMAT,
}
