// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.catalog;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.Collection;
import java.util.Objects;

/** Specification of an online table. */
@Generated
@JsonSerialize(using = OnlineTableSpec.OnlineTableSpecSerializer.class)
@JsonDeserialize(using = OnlineTableSpec.OnlineTableSpecDeserializer.class)
public class OnlineTableSpec {
  /**
   * Whether to create a full-copy pipeline -- a pipeline that stops after creates a full copy of
   * the source table upon initialization and does not process any change data feeds (CDFs)
   * afterwards. The pipeline can still be manually triggered afterwards, but it always perform a
   * full copy of the source table and there are no incremental updates. This mode is useful for
   * syncing views or tables without CDFs to online tables. Note that the full-copy pipeline only
   * supports "triggered" scheduling policy.
   */
  private Boolean performFullCopy;

  /** ID of the associated pipeline. Generated by the server - cannot be set by the caller. */
  private String pipelineId;

  /** Primary Key columns to be used for data insert/update in the destination. */
  private Collection<String> primaryKeyColumns;

  /** Pipeline runs continuously after generating the initial data. */
  private OnlineTableSpecContinuousSchedulingPolicy runContinuously;

  /**
   * Pipeline stops after generating the initial data and can be triggered later (manually, through
   * a cron job or through data triggers)
   */
  private OnlineTableSpecTriggeredSchedulingPolicy runTriggered;

  /** Three-part (catalog, schema, table) name of the source Delta table. */
  private String sourceTableFullName;

  /** Time series key to deduplicate (tie-break) rows with the same primary key. */
  private String timeseriesKey;

  public OnlineTableSpec setPerformFullCopy(Boolean performFullCopy) {
    this.performFullCopy = performFullCopy;
    return this;
  }

  public Boolean getPerformFullCopy() {
    return performFullCopy;
  }

  public OnlineTableSpec setPipelineId(String pipelineId) {
    this.pipelineId = pipelineId;
    return this;
  }

  public String getPipelineId() {
    return pipelineId;
  }

  public OnlineTableSpec setPrimaryKeyColumns(Collection<String> primaryKeyColumns) {
    this.primaryKeyColumns = primaryKeyColumns;
    return this;
  }

  public Collection<String> getPrimaryKeyColumns() {
    return primaryKeyColumns;
  }

  public OnlineTableSpec setRunContinuously(
      OnlineTableSpecContinuousSchedulingPolicy runContinuously) {
    this.runContinuously = runContinuously;
    return this;
  }

  public OnlineTableSpecContinuousSchedulingPolicy getRunContinuously() {
    return runContinuously;
  }

  public OnlineTableSpec setRunTriggered(OnlineTableSpecTriggeredSchedulingPolicy runTriggered) {
    this.runTriggered = runTriggered;
    return this;
  }

  public OnlineTableSpecTriggeredSchedulingPolicy getRunTriggered() {
    return runTriggered;
  }

  public OnlineTableSpec setSourceTableFullName(String sourceTableFullName) {
    this.sourceTableFullName = sourceTableFullName;
    return this;
  }

  public String getSourceTableFullName() {
    return sourceTableFullName;
  }

  public OnlineTableSpec setTimeseriesKey(String timeseriesKey) {
    this.timeseriesKey = timeseriesKey;
    return this;
  }

  public String getTimeseriesKey() {
    return timeseriesKey;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    OnlineTableSpec that = (OnlineTableSpec) o;
    return Objects.equals(performFullCopy, that.performFullCopy)
        && Objects.equals(pipelineId, that.pipelineId)
        && Objects.equals(primaryKeyColumns, that.primaryKeyColumns)
        && Objects.equals(runContinuously, that.runContinuously)
        && Objects.equals(runTriggered, that.runTriggered)
        && Objects.equals(sourceTableFullName, that.sourceTableFullName)
        && Objects.equals(timeseriesKey, that.timeseriesKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        performFullCopy,
        pipelineId,
        primaryKeyColumns,
        runContinuously,
        runTriggered,
        sourceTableFullName,
        timeseriesKey);
  }

  @Override
  public String toString() {
    return new ToStringer(OnlineTableSpec.class)
        .add("performFullCopy", performFullCopy)
        .add("pipelineId", pipelineId)
        .add("primaryKeyColumns", primaryKeyColumns)
        .add("runContinuously", runContinuously)
        .add("runTriggered", runTriggered)
        .add("sourceTableFullName", sourceTableFullName)
        .add("timeseriesKey", timeseriesKey)
        .toString();
  }

  OnlineTableSpecPb toPb() {
    OnlineTableSpecPb pb = new OnlineTableSpecPb();
    pb.setPerformFullCopy(performFullCopy);
    pb.setPipelineId(pipelineId);
    pb.setPrimaryKeyColumns(primaryKeyColumns);
    pb.setRunContinuously(runContinuously);
    pb.setRunTriggered(runTriggered);
    pb.setSourceTableFullName(sourceTableFullName);
    pb.setTimeseriesKey(timeseriesKey);

    return pb;
  }

  static OnlineTableSpec fromPb(OnlineTableSpecPb pb) {
    OnlineTableSpec model = new OnlineTableSpec();
    model.setPerformFullCopy(pb.getPerformFullCopy());
    model.setPipelineId(pb.getPipelineId());
    model.setPrimaryKeyColumns(pb.getPrimaryKeyColumns());
    model.setRunContinuously(pb.getRunContinuously());
    model.setRunTriggered(pb.getRunTriggered());
    model.setSourceTableFullName(pb.getSourceTableFullName());
    model.setTimeseriesKey(pb.getTimeseriesKey());

    return model;
  }

  public static class OnlineTableSpecSerializer extends JsonSerializer<OnlineTableSpec> {
    @Override
    public void serialize(OnlineTableSpec value, JsonGenerator gen, SerializerProvider provider)
        throws IOException {
      OnlineTableSpecPb pb = value.toPb();
      provider.defaultSerializeValue(pb, gen);
    }
  }

  public static class OnlineTableSpecDeserializer extends JsonDeserializer<OnlineTableSpec> {
    @Override
    public OnlineTableSpec deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException {
      // The Codec is set by us in the SerDeUtils.java, and it is an ObjectMapper.
      ObjectMapper mapper = (ObjectMapper) p.getCodec();
      OnlineTableSpecPb pb = mapper.readValue(p, OnlineTableSpecPb.class);
      return OnlineTableSpec.fromPb(pb);
    }
  }
}
