// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.catalog;

import com.databricks.sdk.support.Generated;

@Generated
public enum SpecialDestination {
  SPECIAL_DESTINATION_CATALOG_OWNER,
  SPECIAL_DESTINATION_CONNECTION_OWNER,
  SPECIAL_DESTINATION_CREDENTIAL_OWNER,
  SPECIAL_DESTINATION_EXTERNAL_LOCATION_OWNER,
  SPECIAL_DESTINATION_FUNCTION_OWNER,
  SPECIAL_DESTINATION_METASTORE_OWNER,
  SPECIAL_DESTINATION_REGISTERED_MODEL_OWNER,
  SPECIAL_DESTINATION_SCHEMA_OWNER,
  SPECIAL_DESTINATION_TABLE_OWNER,
  SPECIAL_DESTINATION_VOLUME_OWNER,
}
