// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.oauth2;

import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/**
 * <p>CreateCustomAppIntegrationOutput class.</p>
 *
 * @author tanmay.rustagi
 * @version $Id: $Id
 */
public class CreateCustomAppIntegrationOutput {
  /** oauth client-id generated by the Databricks */
  @JsonProperty("client_id")
  private String clientId;

  /**
   * oauth client-secret generated by the Databricks if this is a confidential oauth app
   * client-secret will be generated.
   */
  @JsonProperty("client_secret")
  private String clientSecret;

  /** unique integration id for the custom oauth app */
  @JsonProperty("integration_id")
  private String integrationId;

  /**
   * <p>Setter for the field <code>clientId</code>.</p>
   *
   * @param clientId a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.oauth2.CreateCustomAppIntegrationOutput} object
   */
  public CreateCustomAppIntegrationOutput setClientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * <p>Getter for the field <code>clientId</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getClientId() {
    return clientId;
  }

  /**
   * <p>Setter for the field <code>clientSecret</code>.</p>
   *
   * @param clientSecret a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.oauth2.CreateCustomAppIntegrationOutput} object
   */
  public CreateCustomAppIntegrationOutput setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

  /**
   * <p>Getter for the field <code>clientSecret</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getClientSecret() {
    return clientSecret;
  }

  /**
   * <p>Setter for the field <code>integrationId</code>.</p>
   *
   * @param integrationId a {@link java.lang.String} object
   * @return a {@link com.databricks.sdk.service.oauth2.CreateCustomAppIntegrationOutput} object
   */
  public CreateCustomAppIntegrationOutput setIntegrationId(String integrationId) {
    this.integrationId = integrationId;
    return this;
  }

  /**
   * <p>Getter for the field <code>integrationId</code>.</p>
   *
   * @return a {@link java.lang.String} object
   */
  public String getIntegrationId() {
    return integrationId;
  }

  /** {@inheritDoc} */
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    CreateCustomAppIntegrationOutput that = (CreateCustomAppIntegrationOutput) o;
    return Objects.equals(clientId, that.clientId)
        && Objects.equals(clientSecret, that.clientSecret)
        && Objects.equals(integrationId, that.integrationId);
  }

  /** {@inheritDoc} */
  @Override
  public int hashCode() {
    return Objects.hash(clientId, clientSecret, integrationId);
  }

  /** {@inheritDoc} */
  @Override
  public String toString() {
    return new ToStringer(CreateCustomAppIntegrationOutput.class)
        .add("clientId", clientId)
        .add("clientSecret", clientSecret)
        .add("integrationId", integrationId)
        .toString();
  }
}
