// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.oauth2;

import java.util.Map;

import com.databricks.sdk.annotation.QueryParam;
import com.fasterxml.jackson.annotation.JsonProperty;



public class CreateCustomAppIntegrationOutput {
    /**
     * oauth client-id generated by the Databricks
     */
    @JsonProperty("client_id")
    private String clientId;
    
    /**
     * oauth client-secret generated by the Databricks if this is a confidential
     * oauth app client-secret will be generated.
     */
    @JsonProperty("client_secret")
    private String clientSecret;
    
    /**
     * unique integration id for the custom oauth app
     */
    @JsonProperty("integration_id")
    private String integrationId;
    
    public CreateCustomAppIntegrationOutput setClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }

    public String getClientId() {
        return clientId;
    }
    
    public CreateCustomAppIntegrationOutput setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
        return this;
    }

    public String getClientSecret() {
        return clientSecret;
    }
    
    public CreateCustomAppIntegrationOutput setIntegrationId(String integrationId) {
        this.integrationId = integrationId;
        return this;
    }

    public String getIntegrationId() {
        return integrationId;
    }
    
}
