// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.disasterrecovery;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/**
 * A stable URL provides a failover-aware endpoint for accessing a workspace. Its lifecycle is
 * independent of any failover group.
 */
@Generated
public class StableUrl {
  /**
   * Fully qualified resource name of the FailoverGroup this stable URL is currently linked to, in
   * the format `accounts/{account_id}/failover-groups/{failover_group_id}`. Empty when the stable
   * URL is not attached to any failover group. Server-controlled: written by CreateFailoverGroup /
   * UpdateFailoverGroup on link, cleared by DeleteFailoverGroup / UpdateFailoverGroup on unlink.
   */
  @JsonProperty("failover_group_name")
  private String failoverGroupName;

  /**
   * The workspace this stable URL is initially bound to. Used only in Create requests to associate
   * the stable URL with a workspace. Not returned in responses. Mirrors
   * FailoverGroup.initial_primary_region semantics.
   */
  @JsonProperty("initial_workspace_id")
  private String initialWorkspaceId;

  /** Fully qualified resource name. Format: accounts/{account_id}/stable-urls/{stable_url_id}. */
  @JsonProperty("name")
  private String name;

  /**
   * The stable URL endpoint. Generated by the backend on creation and immutable thereafter. For
   * non-Private-Link workspaces this is `https://<spog_host>/?c=<connection_id>`. For Private-Link
   * workspaces this is the per-connection hostname.
   */
  @JsonProperty("url")
  private String url;

  public StableUrl setFailoverGroupName(String failoverGroupName) {
    this.failoverGroupName = failoverGroupName;
    return this;
  }

  public String getFailoverGroupName() {
    return failoverGroupName;
  }

  public StableUrl setInitialWorkspaceId(String initialWorkspaceId) {
    this.initialWorkspaceId = initialWorkspaceId;
    return this;
  }

  public String getInitialWorkspaceId() {
    return initialWorkspaceId;
  }

  public StableUrl setName(String name) {
    this.name = name;
    return this;
  }

  public String getName() {
    return name;
  }

  public StableUrl setUrl(String url) {
    this.url = url;
    return this;
  }

  public String getUrl() {
    return url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    StableUrl that = (StableUrl) o;
    return Objects.equals(failoverGroupName, that.failoverGroupName)
        && Objects.equals(initialWorkspaceId, that.initialWorkspaceId)
        && Objects.equals(name, that.name)
        && Objects.equals(url, that.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failoverGroupName, initialWorkspaceId, name, url);
  }

  @Override
  public String toString() {
    return new ToStringer(StableUrl.class)
        .add("failoverGroupName", failoverGroupName)
        .add("initialWorkspaceId", initialWorkspaceId)
        .add("name", name)
        .add("url", url)
        .toString();
  }
}
