// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package com.databricks.sdk.service.networking;

import com.databricks.sdk.support.Generated;
import com.databricks.sdk.support.ToStringer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.protobuf.Timestamp;
import java.util.Objects;

/**
 * Endpoint represents a cloud networking resource in a user's cloud account and binds it to the
 * Databricks account.
 */
@Generated
public class Endpoint {
  /** The Databricks Account in which the endpoint object exists. */
  @JsonProperty("account_id")
  private String accountId;

  /** Info for an Azure private endpoint. */
  @JsonProperty("azure_private_endpoint_info")
  private AzurePrivateEndpointInfo azurePrivateEndpointInfo;

  /**
   * The timestamp when the endpoint was created. The timestamp is in RFC 3339 format in UTC
   * timezone.
   */
  @JsonProperty("create_time")
  private Timestamp createTime;

  /**
   * The human-readable display name of this endpoint. The input should conform to RFC-1034, which
   * restricts to letters, numbers, and hyphens, with the first character a letter, the last a
   * letter or a number, and a 63 character maximum.
   */
  @JsonProperty("display_name")
  private String displayName;

  /**
   * The unique identifier for this endpoint under the account. This field is a UUID generated by
   * Databricks.
   */
  @JsonProperty("endpoint_id")
  private String endpointId;

  /** The resource name of the endpoint, which uniquely identifies the endpoint. */
  @JsonProperty("name")
  private String name;

  /** The cloud provider region where this endpoint is located. */
  @JsonProperty("region")
  private String region;

  /** The state of the endpoint. The endpoint can only be used if the state is `APPROVED`. */
  @JsonProperty("state")
  private EndpointState state;

  /**
   * The use case that determines the type of network connectivity this endpoint provides. This
   * field is automatically determined based on the endpoint configuration and cloud-specific
   * settings.
   */
  @JsonProperty("use_case")
  private EndpointUseCase useCase;

  public Endpoint setAccountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

  public String getAccountId() {
    return accountId;
  }

  public Endpoint setAzurePrivateEndpointInfo(AzurePrivateEndpointInfo azurePrivateEndpointInfo) {
    this.azurePrivateEndpointInfo = azurePrivateEndpointInfo;
    return this;
  }

  public AzurePrivateEndpointInfo getAzurePrivateEndpointInfo() {
    return azurePrivateEndpointInfo;
  }

  public Endpoint setCreateTime(Timestamp createTime) {
    this.createTime = createTime;
    return this;
  }

  public Timestamp getCreateTime() {
    return createTime;
  }

  public Endpoint setDisplayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

  public String getDisplayName() {
    return displayName;
  }

  public Endpoint setEndpointId(String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  public String getEndpointId() {
    return endpointId;
  }

  public Endpoint setName(String name) {
    this.name = name;
    return this;
  }

  public String getName() {
    return name;
  }

  public Endpoint setRegion(String region) {
    this.region = region;
    return this;
  }

  public String getRegion() {
    return region;
  }

  public Endpoint setState(EndpointState state) {
    this.state = state;
    return this;
  }

  public EndpointState getState() {
    return state;
  }

  public Endpoint setUseCase(EndpointUseCase useCase) {
    this.useCase = useCase;
    return this;
  }

  public EndpointUseCase getUseCase() {
    return useCase;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Endpoint that = (Endpoint) o;
    return Objects.equals(accountId, that.accountId)
        && Objects.equals(azurePrivateEndpointInfo, that.azurePrivateEndpointInfo)
        && Objects.equals(createTime, that.createTime)
        && Objects.equals(displayName, that.displayName)
        && Objects.equals(endpointId, that.endpointId)
        && Objects.equals(name, that.name)
        && Objects.equals(region, that.region)
        && Objects.equals(state, that.state)
        && Objects.equals(useCase, that.useCase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        accountId,
        azurePrivateEndpointInfo,
        createTime,
        displayName,
        endpointId,
        name,
        region,
        state,
        useCase);
  }

  @Override
  public String toString() {
    return new ToStringer(Endpoint.class)
        .add("accountId", accountId)
        .add("azurePrivateEndpointInfo", azurePrivateEndpointInfo)
        .add("createTime", createTime)
        .add("displayName", displayName)
        .add("endpointId", endpointId)
        .add("name", name)
        .add("region", region)
        .add("state", state)
        .add("useCase", useCase)
        .toString();
  }
}
