name: Integration Tests Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  start-check:
    runs-on: ubuntu-latest
    permissions:
      checks: write   # Permission to create a Check Run
      actions: write  # Permission to run another workflow
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create Check
        id: checkrun
        env:
          GH_TOKEN: ${{ github.token }} # Expose the token for GH CLI
        run: |
          # Due to GitHub limitations, the check is assigned randomly to a check suit
          # https://github.com/orgs/community/discussions/24616
          CHECKID=$(gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f name='Integration Tests' \
            -f head_sha='${{ github.event.pull_request.head.sha }}' \
            -f status='queued' \
            -f 'output[title]=Run Integration Tests' \
            -f 'output[summary]=Running Integration Tests for Java SDK' \
            --jq '.id' \
            /repos/${{ github.repository }}/check-runs)
          
          # Put the ID into a step variable
          echo "checkId=$CHECKID" >> $GITHUB_OUTPUT          

      - name: Trigger Workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # By default, this will run the workflow in the main branch. 
          # To test changes the ref to the current branch.
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'inputs[check_run_id]=${{ steps.checkrun.outputs.checkId }}' \
            -f 'inputs[pull_request_number]=${{ github.events.pull_request.number }}' \
            -f "ref=${{ steps.extract_branch.outputs.branch }}" \
            /repos/${{ github.repository }}/actions/workflows/sdk-nightly.yml/dispatches