name: build

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 11

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Configure Maven proxy
        run: mkdir -p ~/.m2 && cp .github/maven-settings.xml ~/.m2/settings.xml

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Check formatting
        run: mvn --errors spotless:check

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        java-version: [8, 11, 17, 20] # 20 is the latest version as of 2023 and 17 is the latest LTS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up JDK
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: ${{ matrix.java-version }}

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Configure Maven proxy
        run: mkdir -p ~/.m2 && cp .github/maven-settings.xml ~/.m2/settings.xml

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Check Unit Tests
        run: mvn --errors test

  check-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 11

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Configure Maven proxy
        run: mkdir -p ~/.m2 && cp .github/maven-settings.xml ~/.m2/settings.xml

      - name: Validate lockfile
        run: make check-lock
