name: build

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  id-token: write
  contents: read

jobs:
  fmt:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          # google-java-format 1.27.0 (pinned in pom.xml) requires JRE 17+ to run.
          java-version: 17

      - name: Check formatting
        run: mvn --errors spotless:check

      - name: Check for JFrog proxy URLs in lockfiles
        run: |
          make fix-lockfile
          git diff --exit-code -- '**/lockfile.json'

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        java-version: [8, 11, 17, 20] # 20 is the latest version as of 2023 and 17 is the latest LTS
        include:
          - os: ubuntu-latest
            runner:
              group: databricks-protected-runner-group
              labels: linux-ubuntu-latest
          - os: macos-latest
            runner: macos-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          java-version: ${{ matrix.java-version }}

      - name: Check Unit Tests
        run: mvn --errors test

  check-lock:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          java-version: 11

      - name: Validate lockfile
        run: make check-lock
